The datasets used are International Movies Database (IMDB) Data.

The basic analysis we are going to answer throughout are:

1. Which are the highest grossing movies within the data?
2. Which movies have the highest average user vote?
3. Which movies have the most 'polarised' votes?
4. Which movies have the largest vote difference by sex?
5. What is the gross income per director?

Inorder to answer these questions.Please complete the below questions.

1. Import the necessary module(pandas)
2. Apply these settings in order to display contents better

- These are just some display settings

pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)


- Display floating points in a more readable format

pd.options.display.float_format = '{:,.2f}'.format

3. Read the movie's data.
4. Take a look at the schema using info()
5. select certain columns from a dataframe we specify them as a list of strings within square brackets(columns needed - director,genre,original_title)

1. Import the necessary module(pandas)

In [1]:
import pandas as pd

2. Apply these settings in order to display contents better

These are just some display settings

- pd.set_option('display.max_columns', None)
- pd.set_option('display.max_colwidth', None)

In [2]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)

Display floating points in a more readable format

- pd.options.display.float_format = '{:,.2f}'.format

In [3]:
pd.options.display.float_format = '{:,.2f}'.format

3. Read the movie's data.

In [4]:
mov = pd.read_csv("IMDb movies.csv")
mov

C:\Users\sahay\AppData\Local\Temp\ipykernel_25168\4123409485.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  mov = pd.read_csv("IMDb movies.csv")

,imdb_title_id,title,original_title,year,date_published,genre,duration,country,language,director,writer,production_company,actors,description,avg_vote,votes,budget,usa_gross_income,worlwide_gross_income,metascore,reviews_from_users,reviews_from_critics
0,tt0000009,Miss Jerry,Miss Jerry,1894,1894-10-09,Romance,45,USA,NaN,Alexander Black,Alexander Black,Alexander Black Photoplays,"Blanche Bayliss, William Courtenay, Chauncey Depew",The adventures of a female reporter in the 1890s.,5.90,154,NaN,NaN,NaN,NaN,1.00,2.00
1,tt0000574,The Story of the Kelly Gang,The Story of the Kelly Gang,1906,1906-12-26,"Biography, Crime, Drama",70,Australia,NaN,Charles Tait,Charles Tait,J. and N. Tait,"Elizabeth Tait, John Tait, Norman Campbell, Bella Cola, Will Coyne, Sam Crewes, Jack Ennis, John Forde, Vera Linden, Mr. Marshall, Mr. McKenzie, Frank Mills, Ollie Wilson",True story of notorious Australian outlaw Ned Kelly (1855-80).,6.10,589,$ 2250,NaN,NaN,NaN,7.00,7.00
2,tt0001892,Den sorte drøm,Den sorte drøm,1911,1911-08-19,Drama,53,"Germany, Denmark",NaN,Urban Gad,"Urban Gad, Gebhard Schätzler-Perasini",Fotorama,"Asta Nielsen, Valdemar Psilander, Gunnar Helsengreen, Emil Albes, Hugo Flink, Mary Hagen","Two men of high rank are both wooing the beautiful and famous equestrian acrobat Stella. While Stella ignores the jeweler Hirsch, she accepts Count von Waldberg's offer to follow her home, ...",5.80,188,NaN,NaN,NaN,NaN,5.00,2.00
3,tt0002101,Cleopatra,Cleopatra,1912,1912-11-13,"Drama, History",100,USA,English,Charles L. Gaskill,Victorien Sardou,Helen Gardner Picture Players,"Helen Gardner, Pearl Sindelar, Miss Fielding, Miss Robson, Helene Costello, Charles Sindelar, Mr. Howard, James R. Waite, Mr. Osborne, Harry Knowles, Mr. Paul, Mr. Brady, Mr. Corker",The fabled queen of Egypt's affair with Roman general Marc Antony is ultimately disastrous for both of them.,5.20,446,$ 45000,NaN,NaN,NaN,25.00,3.00
4,tt0002130,L'Inferno,L'Inferno,1911,1911-03-06,"Adventure, Drama, Fantasy",68,Italy,Italian,"Francesco Bertolini, Adolfo Padovan",Dante Alighieri,Milano Film,"Salvatore Papa, Arturo Pirovano, Giuseppe de Liguoro, Pier Delle Vigne, Augusto Milla, Attilio Motta, Emilise Beretta",Loosely adapted from Dante's Divine Comedy and inspired by the illustrations of Gustav Doré the original silent film has been restored and has a new score by Tangerine Dream.,7.00,2237,NaN,NaN,NaN,NaN,31.00,14.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85850,tt9908390,Le lion,Le lion,2020,2020-01-29,Comedy,95,"France, Belgium",French,Ludovic Colbeau-Justin,"Alexandre Coquelle, Matthieu Le Naour",Monkey Pack Films,"Dany Boon, Philippe Katerine, Anne Serra, Samuel Jouy, Sophie Verbeeck, Carole Brana, Benoît Pétré, Aksel Ustun, Mathieu Lardot, Olivier Sa, Julien Prevost, Antoine Mathieu, David Ban, Stan, Guillaume Clémencin","A psychiatric hospital patient pretends to be crazy. In charge of caring for this patient, a caregiver will begin to doubt the mental state of his ""protégé"".",5.30,398,NaN,NaN,$ 3507171,NaN,NaN,4.00
85851,tt9911196,De Beentjes van Sint-Hildegard,De Beentjes van Sint-Hildegard,2020,2020-02-13,"Comedy, Drama",103,Netherlands,"German, Dutch",Johan Nijenhuis,"Radek Bajgar, Herman Finkers",Johan Nijenhuis & Co,"Herman Finkers, Johanna ter Steege, Leonie ter Braak, Stef Assen, Annie Beumers, Jos Brummelhuis, Reinier Bulder, Daphne Bunskoek, Karlijn Koel, Karlijn Lansink, Marieke Lustenhouwer, Jan Roerink, Ferdi Stofmeel, Aniek Stokkers, Belinda van der Stoep","A middle-aged veterinary surgeon believes his wife pampers him too much. In order to get away from her, he fakes the onset of dementia.",7.70,724,NaN,NaN,$ 7299062,NaN,6.00,4.00
85852,tt9911774,Padmavyuhathile Abhimanyu,Padmavyuhathile Abhimanyu,2019,2019-03-08,Drama,130,India,Malayalam,Vineesh Aaradya,"Vineesh Aaradya, Vineesh Aaradya",RMCC Productions,"Anoop Chandran, Indrans, Sona Nair, Simon Britto Rodrigues",NaN,7.90,265,NaN,NaN,NaN,NaN,NaN,NaN
85853,tt9914286,Sokagin Çocuklari,Sokagin Çocuklari,2019,2019-03-15,"Drama, Family",98,Turkey,Turkish,Ahmet Faik Akinci,"Ahmet Faik Akinci, Kasim Uçkan",Gizem Ajans,"Ahmet Faik Akinci, Belma Mamati, Metin Keçeci, Burhan Sirmabiyik, Orhan Aydin, Tevfik Yapici, Yusuf Eksi, Toygun Ates, Aziz Özuysal, Dilek Ölekli, Arcan Bunial, Seval Hislisoy, Ergül Çolakoglu, Gülçin Ugur, Ibrahim Balaban",NaN,6.40,194,NaN,NaN,$ 2833,NaN,NaN,NaN
85854,tt9914942,La vida sense la Sara Amat,La vida sense la Sara Amat,2019,2020-02-05,Drama,74,Spain,Catalan,Laura Jou,"Coral Cruz, Pep Puig",La Xarxa de Comunicació Local,"Maria Morera Colomer, Biel Rossell Pelfort, Isaac Alcayde, Lluís Altés, Joan Amargós, Pepo Blasco, Cesc Casanovas, Oriol Cervera, Pau Escobar, Jordi Figueras, Arés Fuster, Judit Martín, Martí Múrcia, Mariona Pagès, Francesca Piñón","Pep, a 13-year-old boy, is in love with a girl from his grandparents village, Sara Amat. One summer night Sara disappears without a trace. After a few hours, Pep finds her hiding in his room.",6.70,102,NaN,NaN,$ 59794,NaN,NaN,2.00

4. Take a look at the schema using info()

In [5]:
mov.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 85855 entries, 0 to 85854
Data columns (total 22 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   imdb_title_id          85855 non-null  object
 1   title                  85855 non-null  object
 2   original_title         85855 non-null  object
 3   year                   85855 non-null  object
 4   date_published         85855 non-null  object
 5   genre                  85855 non-null  object
 6   duration               85855 non-null  int64
 7   country                85791 non-null  object
 8   language               84954 non-null  object
 9   director               85768 non-null  object
 10  writer                 84283 non-null  object
 11  production_company     81400 non-null  object
 12  actors                 85786 non-null  object
 13  description            83740 non-null  object
 14  avg_vote               85855 non-null  float64
 15  votes                  85855 non-null  int64
 16  budget                 23710 non-null  object
 17  usa_gross_income       15326 non-null  object
 18  worlwide_gross_income  31016 non-null  object
 19  metascore              13305 non-null  float64
 20  reviews_from_users     78258 non-null  float64
 21  reviews_from_critics   74058 non-null  float64
dtypes: float64(4), int64(2), object(16)
memory usage: 14.4+ MB

5. select certain columns from a dataframe we specify them as a list of strings within square brackets(columns needed - director,genre,original_title)

In [6]:

print(mov["director"])
print("_______________________________________________________")
print(mov["genre"])
print("_______________________________________________________")
mov["original_title"]

0                            Alexander Black
1                               Charles Tait
2                                  Urban Gad
3                         Charles L. Gaskill
4        Francesco Bertolini, Adolfo Padovan
                        ...
85850                 Ludovic Colbeau-Justin
85851                        Johan Nijenhuis
85852                        Vineesh Aaradya
85853                      Ahmet Faik Akinci
85854                              Laura Jou
Name: director, Length: 85855, dtype: object
_______________________________________________________
0                          Romance
1          Biography, Crime, Drama
2                            Drama
3                   Drama, History
4        Adventure, Drama, Fantasy
                   ...
85850                       Comedy
85851                Comedy, Drama
85852                        Drama
85853                Drama, Family
85854                        Drama
Name: genre, Length: 85855, dtype: object
_______________________________________________________

0                            Miss Jerry
1           The Story of the Kelly Gang
2                        Den sorte drøm
3                             Cleopatra
4                             L'Inferno
                      ...
85850                           Le lion
85851    De Beentjes van Sint-Hildegard
85852         Padmavyuhathile Abhimanyu
85853                 Sokagin Çocuklari
85854        La vida sense la Sara Amat
Name: original_title, Length: 85855, dtype: object

In [7]:
mov.shape

(85855, 22)

1. Which are the highest grossing movies within the data?

In [20]:
mov["worlwide_gross_income"] = mov["worlwide_gross_income"].str.replace('$','')

In [22]:
mov["worlwide_gross_income"] = mov["worlwide_gross_income"].str.replace('INR','')

In [24]:
mov["worlwide_gross_income"] = mov["worlwide_gross_income"].str.replace('PKR','')

In [25]:
mov["worlwide_gross_income"] = mov["worlwide_gross_income"].str.replace('NPR','')

In [26]:
mov["worlwide_gross_income"] = mov["worlwide_gross_income"].str.replace('GBP','')

In [31]:
mov["worlwide_gross_income"] = mov["worlwide_gross_income"].str.replace(',','')

In [32]:
mov["worlwide_gross_income"].dtype

dtype('O')

In [34]:
mov = mov.dropna(subset=["worlwide_gross_income"])
mov["worlwide_gross_income"] = mov["worlwide_gross_income"].astype(int)

C:\Users\sahay\AppData\Local\Temp\ipykernel_25168\359293340.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mov["worlwide_gross_income"] = mov["worlwide_gross_income"].astype(int)

In [35]:
mov["worlwide_gross_income"].dtype

dtype('int64')

In [36]:
highest = mov.sort_values(by="worlwide_gross_income", ascending=False).iloc[0:20]
highest["worlwide_gross_income"]

73865    2797800564
49415    2790439092
31086    2195169869
67523    2068224036
73864    2048359754
43822    1670401444
79633    1656963790
50773    1518814206
68760    1515048151
74934    1450026933
67001    1402808753
62334    1347280838
55353    1342166497
67676    1332540187
76035    1331958159
79934    1300000000
66062    1280803353
68596    1264064380
71919    1242805359
75242    1236005118
Name: worlwide_gross_income, dtype: int64

2. Which movies have the highest average user vote?

In [37]:
highest_avg_vote = mov.sort_values(by="avg_vote", ascending=False).iloc[0:20]
highest_avg_vote[["title", "avg_vote"]]

                                                           title  avg_vote
28453                                       Le ali della libertà      9.30
15528                                                 Il padrino      9.20
79258                                          The Transcendents      9.20
52407                  National Theatre Live: The Lehman Trilogy      9.20
77399                                                  Natsamrat      9.10
48078                                        Il cavaliere oscuro      9.00
83132                                                    Peranbu      9.00
16556                                      Il padrino - Parte II      9.00
84496                                               Anandi Gopal      8.90
28381                                               Pulp Fiction      8.90
27629                                           Schindler's List      8.90
34127                Il Signore degli Anelli - Il ritorno del re      8.90
8973                                        La parola ai giurati      8.90
73869                                               The Crucible      8.90
37623                                                   Kireedam      8.90
85542                                              Ardaas Karaan      8.80
78754                                                Montagna II      8.80
52466                                NT Live: Cyrano de Bergerac      8.80
53529                  Metallica and San Francisco Symphony S&M2      8.80
83933  Distant Sky: Nick Cave & The Bad Seeds Live in Copenhagen      8.80

3. Which movies have the most 'polarised' votes?

In [38]:
most_polarised_votes = mov.sort_values(by="votes", ascending=False).iloc[0:20]
most_polarised_votes[["title", "votes"]]

                                                    title    votes
28453                                Le ali della libertà  2278845
48078                                 Il cavaliere oscuro  2241615
57475                                           Inception  2002816
32487                                          Fight Club  1807440
28381                                        Pulp Fiction  1780147
28066                                        Forrest Gump  1755490
32229                                              Matrix  1632315
31279  Il Signore degli Anelli - La compagnia dell'Anello  1619920
34127         Il Signore degli Anelli - Il ritorno del re  1604280
15528                                          Il padrino  1572674
57234                    Il cavaliere oscuro - Il ritorno  1480582
34128              Il Signore degli Anelli - Le due torri  1449778
50294                                        Interstellar  1449256
29287                                               Seven  1402015
62660                                    Django Unchained  1317856
34440                                       Il gladiatore  1308193
43935                                       Batman Begins  1278075
50773                                        The Avengers  1241220
26257                         Il silenzio degli innocenti  1234134
43404                               Bastardi senza gloria  1229958

5. What is the gross income per director?

In [48]:
director_gross = mov.groupby("director")["worlwide_gross_income"].sum().head(60)
director_gross

director
A. Dean Bell                                               67436
A. Karunakaran                                         149626775
A. Muthu                                                  365318
A. Raven Cruz                                               3700
A. Sarkunam                                               295856
A. Taner Elhan                                           6605310
A.B. Shawky                                                81030
A.J. Edwards                                               70918
A.K. Bir                                                    9188
A.K. Sajan                                                  3735
A.L. Vijay                                                 14766
A.L. Vijay, A.L. Vijay                                   2915137
A.M. Lukas                                                  3861
A.R. Gandhi Krishna                                     50000000
A.R. Murugadoss                                        371270626
A.S. Ravi Kumar Chowdary                               107500000
A.T. White                                                 15849
Aage Rais-Nordentoft                                        4858
Aamir Khan, Amole Gupte                                 21897373
Aanand L. Rai                                           24106621
Aaron Blaise, Robert Walker                            250397798
Aaron Fisher                                                8140
Aaron Harvey                                              301429
Aaron Horvath, Peter Rida Michail                       52090236
Aaron J. Wiederspahn                                       23457
Aaron Katz                                                360006
Aaron Katz, Martha Stephens                               727594
Aaron Kaufman                                              47740
Aaron Keeling, Austin Keeling                             106745
Aaron Kim                                                1553641
Aaron Kim Johnston                                        121548
Aaron Lim, Aaron Lim                                      618400
Aaron Mirtes                                               73605
Aaron Nee, Adam Nee                                        20555
Aaron Norris                                            41169421
Aaron Re                                                    4950
Aaron Rottinghaus                                           3161
Aaron Schimberg                                            17431
Aaron Schneider                                         10522511
Aaron Seltzer, Jason Friedberg                          85749034
Aaron Sorkin                                            59284015
Aaron Wilson                                                8462
Aaron Woodley                                           10931228
Aaron Woolfolk                                             54473
Aarón Fernández Lesur                                     130886
Aashiq Abu                                                778903
Abbas Alibhai Burmawalla, Mastan Alibhai Burmawalla     41372757
Abbas Fahdel                                               11269
Abbas Kiarostami                                         8534578
Abbas Kiarostami, Ken Loach                               367072
Abbas Kiarostami, Shay Modaressi                          562878
Abbas Tyrewala                                          19876703
Abbe Wool                                                 147724
Abby Kohn, Marc Silverstein                             94539426
Abd Al Malik                                              857921
Abdelhamid Bouchnak                                         7500
Abdellah Taia                                              52511
Abdellatif Kechiche                                     38704513
Abderrahmane Sissako                                     8291671
Abdul Malik Abbott                                       2106838
Name: worlwide_gross_income, dtype: int64

In [50]:
highest_gross = 'INR ' + director_gross.sort_values(ascending=False).astype(str)
highest_gross

director
A.R. Murugadoss                                        INR 371270626
Aaron Blaise, Robert Walker                            INR 250397798
A. Karunakaran                                         INR 149626775
A.S. Ravi Kumar Chowdary                               INR 107500000
Abby Kohn, Marc Silverstein                             INR 94539426
Aaron Seltzer, Jason Friedberg                          INR 85749034
Aaron Sorkin                                            INR 59284015
Aaron Horvath, Peter Rida Michail                       INR 52090236
A.R. Gandhi Krishna                                     INR 50000000
Abbas Alibhai Burmawalla, Mastan Alibhai Burmawalla     INR 41372757
Aaron Norris                                            INR 41169421
Abdellatif Kechiche                                     INR 38704513
Aanand L. Rai                                           INR 24106621
Aamir Khan, Amole Gupte                                 INR 21897373
Abbas Tyrewala                                          INR 19876703
Aaron Woodley                                           INR 10931228
Aaron Schneider                                         INR 10522511
Abbas Kiarostami                                         INR 8534578
Abderrahmane Sissako                                     INR 8291671
A. Taner Elhan                                           INR 6605310
A.L. Vijay, A.L. Vijay                                   INR 2915137
Abdul Malik Abbott                                       INR 2106838
Aaron Kim                                                INR 1553641
Abd Al Malik                                              INR 857921
Aashiq Abu                                                INR 778903
Aaron Katz, Martha Stephens                               INR 727594
Aaron Lim, Aaron Lim                                      INR 618400
Abbas Kiarostami, Shay Modaressi                          INR 562878
Abbas Kiarostami, Ken Loach                               INR 367072
A. Muthu                                                  INR 365318
Aaron Katz                                                INR 360006
Aaron Harvey                                              INR 301429
A. Sarkunam                                               INR 295856
Abbe Wool                                                 INR 147724
Aarón Fernández Lesur                                     INR 130886
Aaron Kim Johnston                                        INR 121548
Aaron Keeling, Austin Keeling                             INR 106745
A.B. Shawky                                                INR 81030
Aaron Mirtes                                               INR 73605
A.J. Edwards                                               INR 70918
A. Dean Bell                                               INR 67436
Aaron Woolfolk                                             INR 54473
Abdellah Taia                                              INR 52511
Aaron Kaufman                                              INR 47740
Aaron J. Wiederspahn                                       INR 23457
Aaron Nee, Adam Nee                                        INR 20555
Aaron Schimberg                                            INR 17431
A.T. White                                                 INR 15849
A.L. Vijay                                                 INR 14766
Abbas Fahdel                                               INR 11269
A.K. Bir                                                    INR 9188
Aaron Wilson                                                INR 8462
Aaron Fisher                                                INR 8140
Abdelhamid Bouchnak                                         INR 7500
Aaron Re                                                    INR 4950
Aage Rais-Nordentoft                                        INR 4858
A.M. Lukas                                                  INR 3861
A.K. Sajan                                                  INR 3735
A. Raven Cruz                                               INR 3700
Aaron Rottinghaus                                           INR 3161
Name: worlwide_gross_income, dtype: object